# Generated by Django 4.2.7 on 2024-01-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_customer_address_order_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='products/detail')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.inventory')),
            ],
        ),
    ]
