# Generated by Django 4.2.7 on 2023-09-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.inventory'),
        ),
    ]
