# Generated by Django 4.2.7 on 2024-02-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_becomeseller_trade_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
