# Generated by Django 4.2.7 on 2023-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='picture',
            field=models.ImageField(default='products/default.png', upload_to='products'),
        ),
    ]
