# Generated by Django 4.2.7 on 2024-02-09 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_advance_payment_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bkash_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='nid_card',
            field=models.ImageField(null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 15, 57, 24, 320184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 15, 57, 24, 320184, tzinfo=datetime.timezone.utc)),
        ),
    ]
