# Generated by Django 4.2.7 on 2023-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inventory_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='resale_price',
            field=models.FloatField(default=0.0),
        ),
    ]
