# Generated by Django 4.2.7 on 2024-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
