# Generated by Django 4.2.7 on 2024-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_delivery_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='own_delivery_charge',
            field=models.FloatField(default=0),
        ),
    ]
