# Generated by Django 4.2.7 on 2024-01-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sku',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
