# Generated by Django 4.2.7 on 2024-02-10 11:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_withdraw_bkash_number_withdraw_nid_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='resale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 11, 3, 38, 431523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 11, 3, 38, 431523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.FloatField(default=0.0)),
                ('balance_after', models.FloatField(default=0.0)),
                ('transaction_reference', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 11, 3, 38, 431523, tzinfo=datetime.timezone.utc))),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to='store.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.FloatField(default=0.0)),
                ('balance_after', models.FloatField(default=0.0)),
                ('transaction_reference', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 11, 3, 38, 431523, tzinfo=datetime.timezone.utc))),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_wallets', to='store.currency')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_wallets', to='store.store')),
            ],
        ),
    ]
