# Generated by Django 4.2.7 on 2023-12-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_purchase_resale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resales', to='store.purchase')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resales', to='store.store')),
            ],
        ),
    ]
