# Generated by Django 4.2.7 on 2024-02-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_advance_payment_order_own_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='DRAFT', max_length=200),
        ),
    ]
