# Generated by Django 4.2.7 on 2024-02-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sale_resale_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storewallet',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='wallet',
        ),
        migrations.AddField(
            model_name='storewallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storewallet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=200),
        ),
        migrations.AddField(
            model_name='storewallet',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=200),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=200),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='transaction_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='wallet_type',
            field=models.CharField(choices=[('STORE', 'Store'), ('USER', 'User')], default='STORE', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
