# Generated by Django 4.2.7 on 2024-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
