# Generated by Django 4.2.7 on 2024-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_storewallet_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
