# Generated by Django 4.2.7 on 2024-02-09 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 4, 52, 45, 818233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 4, 52, 45, 818233, tzinfo=datetime.timezone.utc)),
        ),
    ]
