# Generated by Django 4.2.7 on 2024-03-04 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_alter_userwallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.CharField(max_length=200, null=True)),
                ('routing', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.CharField(max_length=200)),
                ('routing', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accounts', to='store.store')),
            ],
        ),
    ]
