version: "3.7"

services:
  app:
    image: farozamart:latest
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farozamart