# Generated by Django 4.2.7 on 2023-12-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteadFastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.IntegerField()),
                ('invoice', models.CharField(max_length=200)),
                ('tracking_code', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
        ),
    ]
