# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile-pictures'),
        ),
    ]
